# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gllu' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   use_frameworks!

  # Pods for gllu

  pod 'FBSDKCoreKit', '4.17'
  pod 'FBSDKLoginKit', '4.17'
  pod 'FBSDKShareKit', '4.17'
  pod 'QBImagePickerController'
  pod 'Flurry-iOS-SDK/FlurrySDK'

end
