var index = 0;

export const countries = [
  { key: index++, label:  'Afghanistan'},
  { key: index++, label:  'Åland Islands'},
  { key: index++, label:  'Albania'},
  { key: index++, label:  'Algeria'},
  { key: index++, label:  'American Samoa'},
  { key: index++, label:  'AndorrA'},
  { key: index++, label:  'Angola'},
  { key: index++, label:  'Anguilla'},
  { key: index++, label:  'Antarctica'},
  { key: index++, label:  'Antigua and Barbuda'},
  { key: index++, label:  'Argentina'},
  { key: index++, label:  'Armenia'},
  { key: index++, label:  'Aruba'},
  { key: index++, label:  'Australia'},
  { key: index++, label:  'Austria'},
  { key: index++, label:  'Azerbaijan'},
  { key: index++, label:  'Bahamas'},
  { key: index++, label:  'Bahrain'},
  { key: index++, label:  'Bangladesh'},
  { key: index++, label:  'Barbados'},
  { key: index++, label:  'Belarus'},
  { key: index++, label:  'Belgium'},
  { key: index++, label:  'Belize'},
  { key: index++, label:  'Benin'},
  { key: index++, label:  'Bermuda'},
  { key: index++, label:  'Bhutan'},
  { key: index++, label:  'Bolivia'},
  { key: index++, label:  'Bosnia and Herzegovina'},
  { key: index++, label:  'Botswana'},
  { key: index++, label:  'Bouvet Island'},
  { key: index++, label:  'Brazil'},
  { key: index++, label:  'British Indian Ocean Territory'},
  { key: index++, label:  'Brunei Darussalam'},
  { key: index++, label:  'Bulgaria'},
  { key: index++, label:  'Burkina Faso'},
  { key: index++, label:  'Burundi'},
  { key: index++, label:  'Cambodia'},
  { key: index++, label:  'Cameroon'},
  { key: index++, label:  'Canada'},
  { key: index++, label:  'Cape Verde'},
  { key: index++, label:  'Cayman Islands'},
  { key: index++, label:  'Central African Republic'},
  { key: index++, label:  'Chad'},
  { key: index++, label:  'Chile'},
  { key: index++, label:  'China'},
  { key: index++, label:  'Christmas Island'},
  { key: index++, label:  'Cocos (Keeling) Islands'},
  { key: index++, label:  'Colombia'},
  { key: index++, label:  'Comoros'},
  { key: index++, label:  'Congo'},
  { key: index++, label:  'Congo, The Democratic Republic of the'},
  { key: index++, label:  'Cook Islands'},
  { key: index++, label:  'Costa Rica'},
  { key: index++, label:  'Cote D\'Ivoire'},
  { key: index++, label:  'Croatia'},
  { key: index++, label:  'Cuba'},
  { key: index++, label:  'Cyprus'},
  { key: index++, label:  'Czech Republic'},
  { key: index++, label:  'Denmark'},
  { key: index++, label:  'Djibouti'},
  { key: index++, label:  'Dominica'},
  { key: index++, label:  'Dominican Republic'},
  { key: index++, label:  'Ecuador'},
  { key: index++, label:  'Egypt'},
  { key: index++, label:  'El Salvador'},
  { key: index++, label:  'Equatorial Guinea'},
  { key: index++, label:  'Eritrea'},
  { key: index++, label:  'Estonia'},
  { key: index++, label:  'Ethiopia'},
  { key: index++, label:  'Falkland Islands (Malvinas)'},
  { key: index++, label:  'Faroe Islands'},
  { key: index++, label:  'Fiji'},
  { key: index++, label:  'Finland'},
  { key: index++, label:  'France'},
  { key: index++, label:  'French Guiana'},
  { key: index++, label:  'French Polynesia'},
  { key: index++, label:  'French Southern Territories'},
  { key: index++, label:  'Gabon'},
  { key: index++, label:  'Gambia'},
  { key: index++, label:  'Georgia'},
  { key: index++, label:  'Germany'},
  { key: index++, label:  'Ghana'},
  { key: index++, label:  'Gibraltar'},
  { key: index++, label:  'Greece'},
  { key: index++, label:  'Greenland'},
  { key: index++, label:  'Grenada'},
  { key: index++, label:  'Guadeloupe'},
  { key: index++, label:  'Guam'},
  { key: index++, label:  'Guatemala'},
  { key: index++, label:  'Guernsey'},
  { key: index++, label:  'Guinea'},
  { key: index++, label:  'Guinea-Bissau'},
  { key: index++, label:  'Guyana'},
  { key: index++, label:  'Haiti'},
  { key: index++, label:  'Heard Island and Mcdonald Islands'},
  { key: index++, label:  'Holy See (Vatican City State)'},
  { key: index++, label:  'Honduras'},
  { key: index++, label:  'Hong Kong'},
  { key: index++, label:  'Hungary'},
  { key: index++, label:  'Iceland'},
  { key: index++, label:  'India'},
  { key: index++, label:  'Indonesia'},
  { key: index++, label:  'Iran, Islamic Republic Of'},
  { key: index++, label:  'Iraq'},
  { key: index++, label:  'Ireland'},
  { key: index++, label:  'Isle of Man'},
  { key: index++, label:  'Israel'},
  { key: index++, label:  'Italy'},
  { key: index++, label:  'Jamaica'},
  { key: index++, label:  'Japan'},
  { key: index++, label:  'Jersey'},
  { key: index++, label:  'Jordan'},
  { key: index++, label:  'Kazakhstan'},
  { key: index++, label:  'Kenya'},
  { key: index++, label:  'Kiribati'},
  { key: index++, label:  'Korea, Democratic People\'S Republic of'},
  { key: index++, label:  'Korea, Republic of'},
  { key: index++, label:  'Kuwait'},
  { key: index++, label:  'Kyrgyzstan'},
  { key: index++, label:  'Lao People\'S Democratic Republic'},
  { key: index++, label:  'Latvia'},
  { key: index++, label:  'Lebanon'},
  { key: index++, label:  'Lesotho'},
  { key: index++, label:  'Liberia'},
  { key: index++, label:  'Libyan Arab Jamahiriya'},
  { key: index++, label:  'Liechtenstein'},
  { key: index++, label:  'Lithuania'},
  { key: index++, label:  'Luxembourg'},
  { key: index++, label:  'Macao'},
  { key: index++, label:  'Macedonia, The Former Yugoslav Republic of'},
  { key: index++, label:  'Madagascar'},
  { key: index++, label:  'Malawi'},
  { key: index++, label:  'Malaysia'},
  { key: index++, label:  'Maldives'},
  { key: index++, label:  'Mali'},
  { key: index++, label:  'Malta'},
  { key: index++, label:  'Marshall Islands'},
  { key: index++, label:  'Martinique'},
  { key: index++, label:  'Mauritania'},
  { key: index++, label:  'Mauritius'},
  { key: index++, label:  'Mayotte'},
  { key: index++, label:  'Mexico'},
  { key: index++, label:  'Micronesia, Federated States of'},
  { key: index++, label:  'Moldova, Republic of'},
  { key: index++, label:  'Monaco'},
  { key: index++, label:  'Mongolia'},
  { key: index++, label:  'Montserrat'},
  { key: index++, label:  'Morocco'},
  { key: index++, label:  'Mozambique'},
  { key: index++, label:  'Myanmar'},
  { key: index++, label:  'Namibia'},
  { key: index++, label:  'Nauru'},
  { key: index++, label:  'Nepal'},
  { key: index++, label:  'Netherlands'},
  { key: index++, label:  'Netherlands Antilles'},
  { key: index++, label:  'New Caledonia'},
  { key: index++, label:  'New Zealand'},
  { key: index++, label:  'Nicaragua'},
  { key: index++, label:  'Niger'},
  { key: index++, label:  'Nigeria'},
  { key: index++, label:  'Niue'},
  { key: index++, label:  'Norfolk Island'},
  { key: index++, label:  'Northern Mariana Islands'},
  { key: index++, label:  'Norway'},
  { key: index++, label:  'Oman'},
  { key: index++, label:  'Pakistan'},
  { key: index++, label:  'Palau'},
  { key: index++, label:  'Palestinian Territory, Occupied'},
  { key: index++, label:  'Panama'},
  { key: index++, label:  'Papua New Guinea'},
  { key: index++, label:  'Paraguay'},
  { key: index++, label:  'Peru'},
  { key: index++, label:  'Philippines'},
  { key: index++, label:  'Pitcairn'},
  { key: index++, label:  'Poland'},
  { key: index++, label:  'Portugal'},
  { key: index++, label:  'Puerto Rico'},
  { key: index++, label:  'Qatar'},
  { key: index++, label:  'Reunion'},
  { key: index++, label:  'Romania'},
  { key: index++, label:  'Russian Federation'},
  { key: index++, label:  'RWANDA'},
  { key: index++, label:  'Saint Helena'},
  { key: index++, label:  'Saint Kitts and Nevis'},
  { key: index++, label:  'Saint Lucia'},
  { key: index++, label:  'Saint Pierre and Miquelon'},
  { key: index++, label:  'Saint Vincent and the Grenadines'},
  { key: index++, label:  'Samoa'},
  { key: index++, label:  'San Marino'},
  { key: index++, label:  'Sao Tome and Principe'},
  { key: index++, label:  'Saudi Arabia'},
  { key: index++, label:  'Senegal'},
  { key: index++, label:  'Serbia and Montenegro'},
  { key: index++, label:  'Seychelles'},
  { key: index++, label:  'Sierra Leone'},
  { key: index++, label:  'Singapore'},
  { key: index++, label:  'Slovakia'},
  { key: index++, label:  'Slovenia'},
  { key: index++, label:  'Solomon Islands'},
  { key: index++, label:  'Somalia'},
  { key: index++, label:  'South Africa'},
  { key: index++, label:  'South Georgia and the South Sandwich Islands'},
  { key: index++, label:  'Spain'},
  { key: index++, label:  'Sri Lanka'},
  { key: index++, label:  'Sudan'},
  { key: index++, label:  'Suriname'},
  { key: index++, label:  'Svalbard and Jan Mayen'},
  { key: index++, label:  'Swaziland'},
  { key: index++, label:  'Sweden'},
  { key: index++, label:  'Switzerland'},
  { key: index++, label:  'Syrian Arab Republic'},
  { key: index++, label:  'Taiwan, Province of China'},
  { key: index++, label:  'Tajikistan'},
  { key: index++, label:  'Tanzania, United Republic of'},
  { key: index++, label:  'Thailand'},
  { key: index++, label:  'Timor-Leste'},
  { key: index++, label:  'Togo'},
  { key: index++, label:  'Tokelau'},
  { key: index++, label:  'Tonga'},
  { key: index++, label:  'Trinidad and Tobago'},
  { key: index++, label:  'Tunisia'},
  { key: index++, label:  'Turkey'},
  { key: index++, label:  'Turkmenistan'},
  { key: index++, label:  'Turks and Caicos Islands'},
  { key: index++, label:  'Tuvalu'},
  { key: index++, label:  'Uganda'},
  { key: index++, label:  'Ukraine'},
  { key: index++, label:  'United Arab Emirates'},
  { key: index++, label:  'United Kingdom'},
  { key: index++, label:  'United States'},
  { key: index++, label:  'United States Minor Outlying Islands'},
  { key: index++, label:  'Uruguay'},
  { key: index++, label:  'Uzbekistan'},
  { key: index++, label:  'Vanuatu'},
  { key: index++, label:  'Venezuela'},
  { key: index++, label:  'Viet Nam'},
  { key: index++, label:  'Virgin Islands, British'},
  { key: index++, label:  'Virgin Islands, U.S.'},
  { key: index++, label:  'Wallis and Futuna'},
  { key: index++, label:  'Western Sahara'},
  { key: index++, label:  'Yemen'},
  { key: index++, label:  'Zambia'},
  { key: index++, label:  'Zimbabwe'}
]